controller_list:
  - name: fake_arm_3_controller
    type: $(arg execution_type)
    joints:
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
initial:  # Define initial robot poses.
  - group: arm_3
    pose: look-down